# Generated by Django 3.2 on 2021-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user_id', models.CharField(max_length=30)),
                ('followed_user_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('tguser_id', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=10, null=True)),
                ('interest', models.CharField(choices=[('ballad', 'Ballad'), ('hiphop', 'Hiphop'), ('pop', 'POP')], max_length=20, null=True)),
                ('profpic', models.ImageField(blank=True, upload_to='user/profilepic')),
                ('introduction', models.TextField(blank=True)),
                ('following', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
                ('concertnum', models.IntegerField(default=0)),
            ],
        ),
    ]
