# Generated by Django 3.2 on 2021-08-03 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_review_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='concertpcp',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=models.JSONField(default=list),
        ),
    ]
