# Generated by Django 3.2 on 2021-08-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210803_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userkey',
        ),
    ]
