# Generated by Django 3.2 on 2021-08-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userinfo_userkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='interests',
        ),
    ]
