# Generated by Django 3.2.6 on 2021-08-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userinfo_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='interests',
            field=models.JSONField(default=list),
        ),
    ]
